// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcclcilexaeriauuwdks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjY2xjaWxleGFlcmlhdXV3ZGtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4OTY0NTUsImV4cCI6MjA3MzQ3MjQ1NX0.HtWiBnNImG35nC_u_2Yt21OnFRV9xOQZssIw5zSeM2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});